#!/usr/bin/env python3
"""crepuscularity-bindgen: generates language bindings from crepuscularity_abi.h."""

import argparse
import os
import re
import sys
from pathlib import Path


def parse_header(header_path):
    with open(header_path) as f:
        content = f.read()
    functions = []
    pattern = r'(?:(?:extern\s+)?(?:const\s+)?)?(\w+(?:\s*\*)?)\s+' \
              r'\*?(\w+)\s*\(' \
              r'([^)]*)\)\s*;'
    for match in re.finditer(pattern, content):
        ret = match.group(1).strip()
        name = match.group(2).strip()
        params_str = match.group(3).strip()
        if name in ('ifndef', 'define', 'include', 'endif', 'CrepusEventCallback'):
            continue
        params = []
        if params_str:
            for p in params_str.split(','):
                p = p.strip()
                if p and p != 'void':
                    parts = p.rsplit(None, 1)
                    if len(parts) == 2:
                        ptype, pname = parts
                        ptype = ptype.replace('*', '').strip()
                        pname = pname.replace('*', '').strip()
                        params.append({'type': ptype, 'name': pname})
                    else:
                        params.append({'type': parts[0], 'name': 'arg'})
        functions.append({'name': name, 'return_type': ret, 'params': params})
    return functions


def gen_python(functions):
    lines = []
    lines.append("# Auto-generated by crepuscularity-bindgen")
    lines.append("")
    lines.append("import ctypes, json, os, sys")
    lines.append("from pathlib import Path")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("")
    lines.append("def _default_lib():")
    lines.append("    root = Path(__file__).resolve().parents[2]")
    lines.append('    suffix = {"darwin": "dylib", "linux": "so", "win32": "dll"}.get(sys.platform, "so")')
    lines.append('    name = "libcrepuscularity_abi." + suffix')
    lines.append('    return str(root / "target" / "debug" / name)')
    lines.append("")
    lines.append("")
    lines.append("class CrepusAbiSession:")
    lines.append('    """Low-level ABI session wrapping libcrepuscularity_abi."""')
    lines.append("")
    lines.append("    def __init__(self, lib_path=None):")
    lines.append('        self._lib = ctypes.CDLL(lib_path or os.environ.get("CREPUS_ABI_LIB") or _default_lib())')
    lines.append("        self._callback_type = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_void_p)")
    lines.append("        self._callback_ref = None")
    lines.append("        self._configure()")
    lines.append("        self._ptr = self._lib.crepus_session_new()")
    lines.append("        if not self._ptr:")
    lines.append("            raise RuntimeError(self._take_global_error())")
    lines.append("")
    lines.append("    def close(self):")
    lines.append("        if hasattr(self, '_ptr') and self._ptr:")
    lines.append("            self._lib.crepus_session_free(self._ptr)")
    lines.append("            self._ptr = None")
    lines.append("")
    lines.append("    def __enter__(self):")
    lines.append("        return self")
    lines.append("")
    lines.append("    def __exit__(self, *args):")
    lines.append("        self.close()")
    lines.append("")
    lines.append("    def __del__(self):")
    lines.append("        self.close()")
    lines.append("")

    for func in functions:
        n = func['name']
        params = func['params']
        ret = func['return_type']
        pnames = ', '.join(p['name'] for p in params)
        if pnames:
            lines.append(f"    def {n}(self, {pnames}):")
        else:
            lines.append(f"    def {n}(self):")
        lines.append(f'        """C ABI: {n}({", ".join(p["name"]+": "+p["type"] for p in params)}) -> {ret}"""')
        lines.append("        pass")
        lines.append("")

    return '\n'.join(lines)


def gen_zig(functions):
    lines = []
    lines.append("//! Auto-generated by crepuscularity-bindgen")
    lines.append("//! Zig bindings for Crepuscularity ABI.")
    lines.append("//! Build with: zig build-exe ... -I<include> -lcrepuscularity_abi")
    lines.append("")
    lines.append("const c = @cImport({")
    lines.append('    @cDefine("CREPUSCULARITY_ABI_H", {});')
    lines.append('    @cInclude("crepuscularity_abi.h");')
    lines.append("});")
    lines.append("")
    lines.append("pub const Session = struct {")
    lines.append("    ptr: ?*c.CrepusSession,")
    lines.append("")
    lines.append("    pub fn init() !Session {")
    lines.append("        const ptr = c.crepus_session_new() orelse return error.AbiFailed;")
    lines.append("        return .{ .ptr = ptr };")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn deinit(self: *Session) void {")
    lines.append("        if (self.ptr) |p| { c.crepus_session_free(p); self.ptr = null; }")
    lines.append("    }")
    lines.append("")

    for func in functions:
        cname = func['name']
        if cname in ('crepus_session_new', 'crepus_session_free', 'crepus_last_error', 'crepus_string_free'):
            continue
        params = func['params']
        ret = func['return_type']
        pnames = [p['name'] for p in params]
        call_args = []
        method_params = ['self: *Session']
        for p in params:
            if p['type'] == 'const' or p['type'] == 'char':
                method_params.append(p['name'] + ': []const u8')
                call_args.append('@ptrCast(' + p['name'] + '.ptr)')
            elif '_callback' in p['name']:
                method_params.append(p['name'] + ': ?*const fn (event_json: []const u8) void')
                call_args.append(p['name'])
            elif p['type'] == 'CrepusEventCallback':
                continue
            else:
                method_params.append(p['name'])
                call_args.append(p['name'])

        method_name = cname.replace('crepus_session_', '')
        method_params_str = ', '.join(method_params)
        call_args_str = ', '.join(call_args)

        lines.append(f"    pub fn {method_name}({method_params_str}) !void {{")
        lines.append(f"        const rc = c.{cname}(self.ptr, {call_args_str});")
        lines.append("        if (rc != 0) return error.AbiFailed;")
        lines.append("    }")
        lines.append("")

    lines.append("};")
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--lang', choices=['python', 'zig'], required=True)
    parser.add_argument('--header', default=None)
    parser.add_argument('--output', '-o', default=None)
    args = parser.parse_args()

    if args.header:
        header_path = args.header
    else:
        script_dir = Path(__file__).resolve().parent
        for parent in [script_dir] + list(script_dir.parents):
            c = parent / 'crates' / 'crepuscularity-abi' / 'include' / 'crepuscularity_abi.h'
            if c.exists():
                header_path = str(c)
                break
        else:
            header_path = str(script_dir / '..' / '..' / 'crates' / 'crepuscularity-abi' / 'include' / 'crepuscularity_abi.h')

    if not os.path.exists(header_path):
        print(f'Error: header not found at {header_path}', file=sys.stderr)
        sys.exit(1)

    functions = parse_header(header_path)
    gens = {'python': gen_python, 'zig': gen_zig}
    output = gens[args.lang](functions)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
            f.write('\n')
    else:
        print(output)


if __name__ == '__main__':
    main()
