[package]
name = "embedded-stm32-f411-ili9341"
version = "0.1.0"
edition = "2021"
publish = false
license = "MPL-2.0"

[workspace]

[dependencies]
crepuscularity-embedded = { path = "../../../crates/crepuscularity-embedded", default-features = false, features = [
    "embassy-stm32",
] }
embassy-stm32 = { version = "0.6.0", features = [
    "defmt",
    "unstable-pac",
    "stm32f411re",
    "memory-x",
    "time-driver-any",
    "exti",
] }
embassy-time = { version = "0.5.1", features = ["defmt", "tick-hz-1_000_000"] }
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "defmt",
] }
embedded-alloc = "0.7.0"
cortex-m-rt = "0.7.3"
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

[profile.release]
opt-level = "s"
lto = true
