//! Framework emit for `crepus web build --emit <target>`.
//!
//! HTML is the real production path (`build_site_wasm`). `--emit moonshine` writes
//! a real `@tschk/crepus-moonshine` app entry. Other non-html emits write scaffolding
//! stubs under `dist/` that map basic View IR kinds onto framework primitives.

use std::fs;
use std::path::PathBuf;
use std::time::Instant;

use crepuscularity_core::context::TemplateContext;
use crepuscularity_native::{render_template_to_ir, to_json_pretty, ViewIr, ViewNode};

use crate::cli::WebEmitTarget;
use crate::ui;

use super::build::{load_all_crepus_public, resolve_emit_paths};

pub(crate) fn build_emit_stub(
    emit: WebEmitTarget,
    site: Option<PathBuf>,
    out_dir: Option<PathBuf>,
    entry: Option<String>,
) {
    let t0 = Instant::now();
    let paths = resolve_emit_paths(site, out_dir, entry);
    let mut files = std::collections::HashMap::new();
    load_all_crepus_public(&paths.site_dir, &paths.site_dir, &mut files);
    if files.is_empty() {
        ui::error(&format!(
            "no .crepus files under {}",
            paths.site_dir.display()
        ));
    }
    let source = files.get(&paths.entry).cloned().unwrap_or_else(|| {
        ui::error(&format!(
            "entry {:?} not found under {}",
            paths.entry,
            paths.site_dir.display()
        ))
    });

    let ctx = TemplateContext::new();
    let ir = render_template_to_ir(&source, &ctx).unwrap_or_else(|e| {
        ui::error(&format!("lower {} to View IR: {e}", paths.entry));
    });

    fs::create_dir_all(&paths.out_dir).unwrap_or_else(|e| {
        ui::error(&format!("mkdir {}: {e}", paths.out_dir.display()));
    });

    let ir_json = to_json_pretty(&ir).unwrap_or_else(|e| {
        ui::error(&format!("serialize View IR: {e}"));
    });
    let ir_path = paths.out_dir.join("crepus-view-ir.json");
    fs::write(&ir_path, &ir_json).unwrap_or_else(|e| {
        ui::error(&format!("write {}: {e}", ir_path.display()));
    });

    let (filename, body) = match emit {
        WebEmitTarget::Html => unreachable!("html uses WASM build path"),
        WebEmitTarget::Moonshine => ("crepus-emit.moonshine.ts", emit_moonshine(&ir_json)),
        WebEmitTarget::Svelte => ("crepus-emit.svelte", emit_svelte(&ir)),
        WebEmitTarget::Solid => ("crepus-emit.solid.tsx", emit_solid(&ir)),
        WebEmitTarget::React => ("crepus-emit.react.tsx", emit_react(&ir)),
    };

    let out_file = paths.out_dir.join(filename);
    fs::write(&out_file, body).unwrap_or_else(|e| {
        ui::error(&format!("write {}: {e}", out_file.display()));
    });

    eprintln!(
        "\n{} wrote {} (+ {})",
        ui::ok(),
        out_file.display(),
        ir_path.display()
    );
    match emit {
        WebEmitTarget::Moonshine => {
            eprintln!(
                "  {} Moonshine emit: App() → renderCrepusIr(ir); install via `crepus moonshine dep`",
                ui::dim("→")
            );
        }
        _ => {
            eprintln!(
                "  {} stub maps View IR kinds → {:?} primitives; wire a real runtime separately",
                ui::dim("→"),
                emit
            );
        }
    }
    ui::done_in(t0.elapsed());
}

/// Emit a Moonshine app entry that renders View IR via `@tschk/crepus-moonshine`.
///
/// `@tschk/crepus-moonshine` currently exports `CrepusIr` (alias `ViewIr` when present).
fn emit_moonshine(ir_json: &str) -> String {
    format!(
        r#"// Generated by crepus web build --emit moonshine
import {{ renderCrepusIr }} from "@tschk/crepus-moonshine";
import type {{ ViewIr }} from "@tschk/crepus-moonshine";

export const ir = {ir_json} as const satisfies ViewIr;

export function App() {{
  return renderCrepusIr(ir);
}}
"#
    )
}

fn emit_svelte(ir: &ViewIr) -> String {
    let kinds = collect_kinds(&ir.root);
    let cases: String = kinds
        .iter()
        .map(|k| format!("    {k}: 'div', // map View IR `{k}` → Svelte element/component\n"))
        .collect();
    format!(
        r#"<!-- Generated by `crepus web build --emit svelte` -->
<script lang="ts">
  export let ir: {{ root: Array<Record<string, unknown>> }};

  const KIND_MAP: Record<string, string> = {{
{cases}  }};

  function tagFor(node: Record<string, unknown>): string {{
    return KIND_MAP[String(node.kind ?? '')] ?? 'div';
  }}
</script>

{{#each ir.root as node}}
  <svelte:element this={{tagFor(node)}} data-crepus-kind={{node.kind}}>
    {{#if node.content}}{{node.content}}{{/if}}
  </svelte:element>
{{/each}}
"#
    )
}

fn emit_solid(ir: &ViewIr) -> String {
    let kinds = collect_kinds(&ir.root);
    let match_arms: String = kinds
        .iter()
        .map(|k| {
            format!(
                "    case {k:?}:\n      return <div data-crepus-kind={k:?}>{{/* TODO: solid {k} */}}</div>;\n"
            )
        })
        .collect();
    format!(
        r#"// Generated by `crepus web build --emit solid`
import {{ For }} from "solid-js";

type ViewNode = {{ kind?: string; content?: string; children?: ViewNode[] }};

export function CrepusView(props: {{ ir: {{ root: ViewNode[] }} }}) {{
  return (
    <For each={{props.ir.root}}>
      {{(node) => <Node node={{node}} />}}
    </For>
  );
}}

function Node(props: {{ node: ViewNode }}) {{
  switch (props.node.kind) {{
{match_arms}    default:
      return <div data-crepus-kind={{props.node.kind}} />;
  }}
}}
"#
    )
}

fn emit_react(ir: &ViewIr) -> String {
    let kinds = collect_kinds(&ir.root);
    let match_arms: String = kinds
        .iter()
        .map(|k| {
            format!(
                "    case {k:?}:\n      return <div data-crepus-kind={k:?}>{{/* TODO: react {k} */}}</div>;\n"
            )
        })
        .collect();
    format!(
        r#"// Generated by `crepus web build --emit react`
import type {{ ReactNode }} from "react";

type ViewNode = {{ kind?: string; content?: string; children?: ViewNode[] }};

export function CrepusView({{ ir }}: {{ ir: {{ root: ViewNode[] }} }}): ReactNode {{
  return <>{{ir.root.map((node, i) => <Node key={{i}} node={{node}} />)}}</>;
}}

function Node({{ node }}: {{ node: ViewNode }}): ReactNode {{
  switch (node.kind) {{
{match_arms}    default:
      return <div data-crepus-kind={{node.kind}} />;
  }}
}}
"#
    )
}

fn collect_kinds(nodes: &[ViewNode]) -> Vec<&'static str> {
    let mut out = Vec::new();
    for n in nodes {
        walk_kinds(n, &mut out);
    }
    out.sort_unstable();
    out.dedup();
    if out.is_empty() {
        out.extend(["text", "stack", "button"]);
    }
    out
}

fn push_kind(out: &mut Vec<&'static str>, kind: &'static str) {
    if !out.contains(&kind) {
        out.push(kind);
    }
}

fn walk_kinds(node: &ViewNode, out: &mut Vec<&'static str>) {
    match node {
        ViewNode::Text { .. } => push_kind(out, "text"),
        ViewNode::If {
            then_children,
            else_children,
            ..
        } => {
            push_kind(out, "if");
            for c in then_children {
                walk_kinds(c, out);
            }
            if let Some(else_children) = else_children {
                for c in else_children {
                    walk_kinds(c, out);
                }
            }
        }
        ViewNode::ForEach { item_body, .. } => {
            push_kind(out, "forEach");
            for c in item_body {
                walk_kinds(c, out);
            }
        }
        ViewNode::Stack { children, .. } => {
            push_kind(out, "stack");
            for c in children {
                walk_kinds(c, out);
            }
        }
        ViewNode::Button { .. } => push_kind(out, "button"),
        ViewNode::Toggle { .. } => push_kind(out, "toggle"),
        ViewNode::Checkbox { .. } => push_kind(out, "checkbox"),
        ViewNode::Slider { .. } => push_kind(out, "slider"),
        ViewNode::Progress { .. } => push_kind(out, "progress"),
        ViewNode::Meter { .. } => push_kind(out, "meter"),
        ViewNode::Badge { .. } => push_kind(out, "badge"),
        ViewNode::Divider { .. } => push_kind(out, "divider"),
        ViewNode::Spacer { .. } => push_kind(out, "spacer"),
        ViewNode::Dropzone { children, .. } => {
            push_kind(out, "dropzone");
            for c in children {
                walk_kinds(c, out);
            }
        }
        ViewNode::FilePicker { .. } => push_kind(out, "filePicker"),
        ViewNode::Image { .. } => push_kind(out, "image"),
        ViewNode::WebView { .. } => push_kind(out, "webView"),
        ViewNode::Scroll { children, .. } => {
            push_kind(out, "scroll");
            for c in children {
                walk_kinds(c, out);
            }
        }
        ViewNode::List { children, .. } => {
            push_kind(out, "list");
            for c in children {
                walk_kinds(c, out);
            }
        }
        ViewNode::ListItem { children, .. } => {
            push_kind(out, "listItem");
            for c in children {
                walk_kinds(c, out);
            }
        }
        ViewNode::SlotRotate { .. } => push_kind(out, "slotRotate"),
        ViewNode::Input { .. } => push_kind(out, "input"),
        ViewNode::Picker { .. } => push_kind(out, "picker"),
        ViewNode::Tabs { tabs, .. } => {
            push_kind(out, "tabs");
            for tab in tabs {
                for c in &tab.children {
                    walk_kinds(c, out);
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_ir() -> ViewIr {
        let source = r#"stack col gap-2
 text "hi"
 button "Go"
"#;
        render_template_to_ir(source, &TemplateContext::new()).expect("ir")
    }

    #[test]
    fn moonshine_emit_uses_tschk_crepus_moonshine() {
        let ir = sample_ir();
        let json = to_json_pretty(&ir).expect("json");
        let body = emit_moonshine(&json);
        assert!(body.contains("@tschk/crepus-moonshine"));
        assert!(body.contains("renderCrepusIr"));
        assert!(body.contains("export function App"));
        assert!(body.contains("satisfies ViewIr"));
        assert!(body.contains("import type { ViewIr }"));
        assert!(body.contains("\"stack\"") || body.contains("stack"));
        // Embedded IR JSON, not a stub placeholder.
        assert!(body.contains("as const satisfies"));
        assert!(!body.contains("TODO"));
    }

    #[test]
    fn react_stub_exports_component() {
        let body = emit_react(&sample_ir());
        assert!(body.contains("export function CrepusView"));
        assert!(body.contains("react"));
    }
}
