/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  sym_frontmatter_marker = 3,
  anon_sym_DASH_DASH_DASH = 4,
  aux_sym_fragment_section_token1 = 5,
  anon_sym_LT = 6,
  aux_sym_jsx_fragment_token1 = 7,
  anon_sym_GT = 8,
  anon_sym_LT_SLASH = 9,
  anon_sym_SLASH_GT = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_token1 = 12,
  aux_sym_quoted_token2 = 13,
  anon_sym_EQ_GT = 14,
  anon_sym__ = 15,
  sym_raw_style_block = 16,
  sym_element_tag = 17,
  anon_sym_LBRACE = 18,
  anon_sym_RBRACE = 19,
  sym_braced_body = 20,
  sym_hash_id = 21,
  sym_attr_name_eq = 22,
  aux_sym_tailwind_pair_token1 = 23,
  aux_sym_plain_class_token1 = 24,
  sym_template = 25,
  sym__eol = 26,
  sym_logical_line = 27,
  sym_fragment_section = 28,
  sym_jsx_fragment = 29,
  sym_quoted = 30,
  sym_match_arm = 31,
  sym_element_line = 32,
  sym_class_segment = 33,
  sym_braced_expression = 34,
  sym_attr_binding_braced = 35,
  sym_attr_binding_quoted = 36,
  sym_attr_name_only = 37,
  sym_tailwind_pair = 38,
  sym_plain_class = 39,
  aux_sym_template_repeat1 = 40,
  aux_sym_quoted_repeat1 = 41,
  aux_sym_element_line_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_frontmatter_marker] = "frontmatter_marker",
  [anon_sym_DASH_DASH_DASH] = "---",
  [aux_sym_fragment_section_token1] = "fragment_section_token1",
  [anon_sym_LT] = "<",
  [aux_sym_jsx_fragment_token1] = "jsx_fragment_token1",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_token1] = "quoted_token1",
  [aux_sym_quoted_token2] = "quoted_token2",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym__] = "_",
  [sym_raw_style_block] = "raw_style_block",
  [sym_element_tag] = "element_tag",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_braced_body] = "braced_body",
  [sym_hash_id] = "hash_id",
  [sym_attr_name_eq] = "attr_name_eq",
  [aux_sym_tailwind_pair_token1] = "tailwind_pair_token1",
  [aux_sym_plain_class_token1] = "plain_class_token1",
  [sym_template] = "template",
  [sym__eol] = "_eol",
  [sym_logical_line] = "logical_line",
  [sym_fragment_section] = "fragment_section",
  [sym_jsx_fragment] = "jsx_fragment",
  [sym_quoted] = "quoted",
  [sym_match_arm] = "match_arm",
  [sym_element_line] = "element_line",
  [sym_class_segment] = "class_segment",
  [sym_braced_expression] = "braced_expression",
  [sym_attr_binding_braced] = "attr_binding_braced",
  [sym_attr_binding_quoted] = "attr_binding_quoted",
  [sym_attr_name_only] = "attr_name_only",
  [sym_tailwind_pair] = "tailwind_pair",
  [sym_plain_class] = "plain_class",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_quoted_repeat1] = "quoted_repeat1",
  [aux_sym_element_line_repeat1] = "element_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_frontmatter_marker] = sym_frontmatter_marker,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [aux_sym_fragment_section_token1] = aux_sym_fragment_section_token1,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_jsx_fragment_token1] = aux_sym_jsx_fragment_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_token1] = aux_sym_quoted_token1,
  [aux_sym_quoted_token2] = aux_sym_quoted_token2,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym__] = anon_sym__,
  [sym_raw_style_block] = sym_raw_style_block,
  [sym_element_tag] = sym_element_tag,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_braced_body] = sym_braced_body,
  [sym_hash_id] = sym_hash_id,
  [sym_attr_name_eq] = sym_attr_name_eq,
  [aux_sym_tailwind_pair_token1] = aux_sym_tailwind_pair_token1,
  [aux_sym_plain_class_token1] = aux_sym_plain_class_token1,
  [sym_template] = sym_template,
  [sym__eol] = sym__eol,
  [sym_logical_line] = sym_logical_line,
  [sym_fragment_section] = sym_fragment_section,
  [sym_jsx_fragment] = sym_jsx_fragment,
  [sym_quoted] = sym_quoted,
  [sym_match_arm] = sym_match_arm,
  [sym_element_line] = sym_element_line,
  [sym_class_segment] = sym_class_segment,
  [sym_braced_expression] = sym_braced_expression,
  [sym_attr_binding_braced] = sym_attr_binding_braced,
  [sym_attr_binding_quoted] = sym_attr_binding_quoted,
  [sym_attr_name_only] = sym_attr_name_only,
  [sym_tailwind_pair] = sym_tailwind_pair,
  [sym_plain_class] = sym_plain_class,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_quoted_repeat1] = aux_sym_quoted_repeat1,
  [aux_sym_element_line_repeat1] = aux_sym_element_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fragment_section_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jsx_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_raw_style_block] = {
    .visible = true,
    .named = true,
  },
  [sym_element_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_braced_body] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_id] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_name_eq] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tailwind_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_class_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_logical_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment_section] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_match_arm] = {
    .visible = true,
    .named = true,
  },
  [sym_element_line] = {
    .visible = true,
    .named = true,
  },
  [sym_class_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_binding_braced] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_binding_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_name_only] = {
    .visible = true,
    .named = true,
  },
  [sym_tailwind_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_class] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attr = 1,
  field_body = 2,
  field_class = 3,
  field_tag = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr] = "attr",
  [field_body] = "body",
  [field_class] = "class",
  [field_tag] = "tag",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag, 0},
  [1] =
    {field_class, 0},
  [2] =
    {field_class, 1, .inherited = true},
    {field_tag, 0},
  [4] =
    {field_attr, 0},
    {field_value, 1},
  [6] =
    {field_class, 0, .inherited = true},
    {field_class, 1, .inherited = true},
  [8] =
    {field_body, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 18,
  [23] = 23,
  [24] = 14,
  [25] = 25,
  [26] = 26,
  [27] = 17,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '\n', 24,
        '"', 40,
        '#', 25,
        '+', 61,
        '-', 63,
        '/', 68,
        '<', 34,
        '=', 69,
        '>', 37,
        '_', 45,
        '{', 53,
        '}', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '<') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'y') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\f' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\f' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(41);
      END_STATE();
    case 20:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '+') ADVANCE(49);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '_') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '#') ADVANCE(70);
      if (lookahead == '@') ADVANCE(67);
      if (lookahead == '{') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '_') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(37);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '<') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '<') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_frontmatter_marker);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_frontmatter_marker);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_fragment_section_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\f' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_fragment_section_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_jsx_fragment_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\f' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_jsx_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_quoted_token2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_quoted_token2);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_raw_style_block);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_element_tag);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_element_tag);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_element_tag);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_element_tag);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_element_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_braced_body);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\f' < lookahead) &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_braced_body);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_hash_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_attr_name_eq);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_tailwind_pair_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '+') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '-') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '.') ADVANCE(67);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead == '[' ||
          lookahead == ']') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '/') ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_plain_class_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 21},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 21},
  [17] = {.lex_state = 21},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 55},
  [36] = {.lex_state = 22},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 17},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 22},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_frontmatter_marker] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_raw_style_block] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_hash_id] = ACTIONS(1),
    [sym_attr_name_eq] = ACTIONS(1),
    [aux_sym_plain_class_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(37),
    [sym__eol] = STATE(2),
    [sym_logical_line] = STATE(26),
    [sym_fragment_section] = STATE(28),
    [sym_jsx_fragment] = STATE(28),
    [sym_quoted] = STATE(23),
    [sym_match_arm] = STATE(28),
    [sym_element_line] = STATE(28),
    [aux_sym_template_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_frontmatter_marker] = ACTIONS(9),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_LT_SLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym__] = ACTIONS(19),
    [sym_raw_style_block] = ACTIONS(5),
    [sym_element_tag] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_frontmatter_marker,
    ACTIONS(11), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym__,
    ACTIONS(21), 1,
      sym_element_tag,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_quoted,
    STATE(25), 1,
      sym_logical_line,
    ACTIONS(25), 2,
      anon_sym_LF,
      sym_raw_style_block,
    STATE(3), 2,
      sym__eol,
      aux_sym_template_repeat1,
    STATE(28), 4,
      sym_fragment_section,
      sym_jsx_fragment,
      sym_match_arm,
      sym_element_line,
  [48] = 14,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_frontmatter_marker,
    ACTIONS(38), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(41), 1,
      anon_sym_LT,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym__,
    ACTIONS(53), 1,
      sym_element_tag,
    STATE(23), 1,
      sym_quoted,
    STATE(33), 1,
      sym_logical_line,
    ACTIONS(29), 2,
      anon_sym_LF,
      sym_raw_style_block,
    STATE(3), 2,
      sym__eol,
      aux_sym_template_repeat1,
    STATE(28), 4,
      sym_fragment_section,
      sym_jsx_fragment,
      sym_match_arm,
      sym_element_line,
  [96] = 10,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_hash_id,
    ACTIONS(67), 1,
      sym_attr_name_eq,
    ACTIONS(70), 1,
      aux_sym_tailwind_pair_token1,
    ACTIONS(73), 1,
      aux_sym_plain_class_token1,
    STATE(4), 1,
      aux_sym_element_line_repeat1,
    STATE(13), 1,
      sym_class_segment,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(11), 7,
      sym_quoted,
      sym_braced_expression,
      sym_attr_binding_braced,
      sym_attr_binding_quoted,
      sym_attr_name_only,
      sym_tailwind_pair,
      sym_plain_class,
  [134] = 10,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      sym_hash_id,
    ACTIONS(84), 1,
      sym_attr_name_eq,
    ACTIONS(86), 1,
      aux_sym_tailwind_pair_token1,
    ACTIONS(88), 1,
      aux_sym_plain_class_token1,
    STATE(6), 1,
      aux_sym_element_line_repeat1,
    STATE(13), 1,
      sym_class_segment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(11), 7,
      sym_quoted,
      sym_braced_expression,
      sym_attr_binding_braced,
      sym_attr_binding_quoted,
      sym_attr_name_only,
      sym_tailwind_pair,
      sym_plain_class,
  [172] = 10,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      sym_hash_id,
    ACTIONS(84), 1,
      sym_attr_name_eq,
    ACTIONS(86), 1,
      aux_sym_tailwind_pair_token1,
    ACTIONS(88), 1,
      aux_sym_plain_class_token1,
    STATE(4), 1,
      aux_sym_element_line_repeat1,
    STATE(13), 1,
      sym_class_segment,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(11), 7,
      sym_quoted,
      sym_braced_expression,
      sym_attr_binding_braced,
      sym_attr_binding_quoted,
      sym_attr_name_only,
      sym_tailwind_pair,
      sym_plain_class,
  [210] = 2,
    ACTIONS(92), 5,
      sym_frontmatter_marker,
      anon_sym_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym__,
      sym_element_tag,
    ACTIONS(27), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      anon_sym_LT_SLASH,
      anon_sym_DQUOTE,
      sym_raw_style_block,
  [226] = 6,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      aux_sym_plain_class_token1,
    STATE(9), 1,
      sym_quoted,
    STATE(15), 1,
      sym_braced_expression,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [249] = 2,
    ACTIONS(100), 1,
      aux_sym_plain_class_token1,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [262] = 2,
    ACTIONS(104), 1,
      aux_sym_plain_class_token1,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [275] = 2,
    ACTIONS(108), 1,
      aux_sym_plain_class_token1,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [288] = 2,
    ACTIONS(112), 1,
      aux_sym_plain_class_token1,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [301] = 2,
    ACTIONS(116), 1,
      aux_sym_plain_class_token1,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [314] = 2,
    ACTIONS(120), 1,
      aux_sym_plain_class_token1,
    ACTIONS(118), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [327] = 2,
    ACTIONS(124), 1,
      aux_sym_plain_class_token1,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [340] = 2,
    ACTIONS(128), 1,
      aux_sym_plain_class_token1,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [353] = 2,
    ACTIONS(132), 1,
      aux_sym_plain_class_token1,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_hash_id,
      sym_attr_name_eq,
      aux_sym_tailwind_pair_token1,
  [366] = 3,
    ACTIONS(134), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(136), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [377] = 3,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(140), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [388] = 3,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(144), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [399] = 3,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(149), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [410] = 3,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(136), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [421] = 2,
    ACTIONS(155), 1,
      anon_sym_EQ_GT,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [429] = 1,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_EQ_GT,
  [435] = 3,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [445] = 3,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [455] = 1,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_EQ_GT,
  [461] = 1,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [466] = 1,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [471] = 1,
    ACTIONS(163), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [476] = 1,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [481] = 1,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [486] = 2,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [493] = 1,
    ACTIONS(163), 1,
      anon_sym_GT,
  [497] = 1,
    ACTIONS(169), 1,
      sym_braced_body,
  [501] = 1,
    ACTIONS(155), 1,
      anon_sym_EQ_GT,
  [505] = 1,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
  [509] = 1,
    ACTIONS(173), 1,
      aux_sym_fragment_section_token1,
  [513] = 1,
    ACTIONS(175), 1,
      aux_sym_jsx_fragment_token1,
  [517] = 1,
    ACTIONS(177), 1,
      aux_sym_jsx_fragment_token1,
  [521] = 1,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 134,
  [SMALL_STATE(6)] = 172,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 226,
  [SMALL_STATE(9)] = 249,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 314,
  [SMALL_STATE(15)] = 327,
  [SMALL_STATE(16)] = 340,
  [SMALL_STATE(17)] = 353,
  [SMALL_STATE(18)] = 366,
  [SMALL_STATE(19)] = 377,
  [SMALL_STATE(20)] = 388,
  [SMALL_STATE(21)] = 399,
  [SMALL_STATE(22)] = 410,
  [SMALL_STATE(23)] = 421,
  [SMALL_STATE(24)] = 429,
  [SMALL_STATE(25)] = 435,
  [SMALL_STATE(26)] = 445,
  [SMALL_STATE(27)] = 455,
  [SMALL_STATE(28)] = 461,
  [SMALL_STATE(29)] = 466,
  [SMALL_STATE(30)] = 471,
  [SMALL_STATE(31)] = 476,
  [SMALL_STATE(32)] = 481,
  [SMALL_STATE(33)] = 486,
  [SMALL_STATE(34)] = 493,
  [SMALL_STATE(35)] = 497,
  [SMALL_STATE(36)] = 501,
  [SMALL_STATE(37)] = 505,
  [SMALL_STATE(38)] = 509,
  [SMALL_STATE(39)] = 513,
  [SMALL_STATE(40)] = 517,
  [SMALL_STATE(41)] = 521,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(21),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(35),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(11),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(8),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_line_repeat1, 2, 0, 5), SHIFT_REPEAT(12),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_line, 1, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_line, 2, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_name_only, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_name_only, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_binding_quoted, 2, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_binding_quoted, 2, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tailwind_pair, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tailwind_pair, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_segment, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_segment, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_class, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_class, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_line_repeat1, 1, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_element_line_repeat1, 1, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_binding_braced, 2, 0, 4),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attr_binding_braced, 2, 0, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_expression, 3, 0, 6),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_expression, 3, 0, 6),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_line, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match_arm, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment_section, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_fragment, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [171] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_crepus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
