[package]
name = "crepuscularity-reactive"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
dom = ["dep:web-sys", "dep:wasm-bindgen", "dep:js-sys"]

[dependencies]
serde_json = "1"
web-sys = { version = "0.3", optional = true, features = [
    "Document",
    "Element",
    "HtmlElement",
    "Window",
    "DomTokenList",
    "Node",
] }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
