[package]
name = "crepuscularity-reactive"
version = "0.1.1"
edition = "2021"
license = "MPL-2.0"
description = "Reactive signals for Crepuscularity WASM clients (UNSTABLE; in active development)."
repository = "https://github.com/tschk/crepuscularity"
documentation = "https://docs.rs/crepuscularity-reactive"
readme = "../../README.md"

[package.metadata.docs.rs]
features = ["dom"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
dom = ["dep:web-sys", "dep:wasm-bindgen", "dep:js-sys"]

[dependencies]
base64 = { workspace = true }
serde_json = { workspace = true }
web-sys = { workspace = true, optional = true, features = [
    "Document",
    "Element",
    "HtmlElement",
    "Window",
    "DomTokenList",
    "Node",
] }
wasm-bindgen = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }

[dev-dependencies]
crepuscularity-core = { path = "../crepuscularity-core", version = "0.4.9" }
