// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// Swift — link libcrepuscularity_abi; expand with SwiftPM module map.
import Foundation

@_silgen_name("crepus_session_new")
func crepus_session_new() -> UnsafeMutableRawPointer?

@_silgen_name("crepus_session_free")
func crepus_session_free(_ session: UnsafeMutableRawPointer?)

@_silgen_name("crepus_session_render_ir_json")
func crepus_session_render_ir_json(_ session: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<CChar>?
