[package]
name = "embedded-stm32-host-sim"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[dependencies]
crepuscularity-embedded = { path = "../../../crates/crepuscularity-embedded", version = "0.1.15", features = ["std", "macros"] }
crepuscularity-embedded-macros = { path = "../../../crates/crepuscularity-embedded-macros", version = "0.1.2" }

[build-dependencies]
crepuscularity-core = { path = "../../../crates/crepuscularity-core", version = "0.4.16" }
