// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

# frozen_string_literal: true
require "fiddle"
require "fiddle/import"

module AbiGenerated
  extend Fiddle::Importer
  dlload ENV.fetch("CREPUS_ABI_LIB", "libcrepuscularity_abi.dylib")
  extern "void* crepus_session_new()"
  extern "void crepus_session_free(void*)"
  extern "char* crepus_session_render_ir_json(void*)"
  extern "void crepus_string_free(char*)"
end
