[[targets]]
type = "lvgl"
id = "stm32-dashboard"
path = "."
template = "ui.crepus"
out = "dist/stm32_dashboard.xml"
name = "Stm32Dashboard"
root = "screen"

[targets.vars]
device = "STM32F411"
panel = "ILI9341"
cpu = 72
status = "nominal"
