/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  anon_sym_LT = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_LT_GT = 5,
  anon_sym_LT_SLASH_GT = 6,
  anon_sym_GT = 7,
  anon_sym_LT_SLASH = 8,
  anon_sym_EQ = 9,
  sym_attr_name = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_token1 = 12,
  aux_sym_quoted_token2 = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  aux_sym_braced_body_token1 = 16,
  sym_text = 17,
  sym_source = 18,
  sym__node = 19,
  sym_jsx_element = 20,
  sym_jsx_self_closing = 21,
  sym_jsx_fragment = 22,
  sym_jsx_open_tag = 23,
  sym_jsx_close_tag = 24,
  sym_attribute = 25,
  sym_attr_binding_quoted = 26,
  sym_attr_binding_braced = 27,
  sym_attr_name_only = 28,
  sym_quoted = 29,
  sym_braced_expression = 30,
  sym_braced_body = 31,
  aux_sym_source_repeat1 = 32,
  aux_sym_jsx_self_closing_repeat1 = 33,
  aux_sym_quoted_repeat1 = 34,
  aux_sym_braced_body_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_LT_SLASH_GT] = "</>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attr_name] = "attr_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_token1] = "quoted_token1",
  [aux_sym_quoted_token2] = "quoted_token2",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_braced_body_token1] = "braced_body_token1",
  [sym_text] = "text",
  [sym_source] = "source",
  [sym__node] = "_node",
  [sym_jsx_element] = "jsx_element",
  [sym_jsx_self_closing] = "jsx_self_closing",
  [sym_jsx_fragment] = "jsx_fragment",
  [sym_jsx_open_tag] = "jsx_open_tag",
  [sym_jsx_close_tag] = "jsx_close_tag",
  [sym_attribute] = "attribute",
  [sym_attr_binding_quoted] = "attr_binding_quoted",
  [sym_attr_binding_braced] = "attr_binding_braced",
  [sym_attr_name_only] = "attr_name_only",
  [sym_quoted] = "quoted",
  [sym_braced_expression] = "braced_expression",
  [sym_braced_body] = "braced_body",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_jsx_self_closing_repeat1] = "jsx_self_closing_repeat1",
  [aux_sym_quoted_repeat1] = "quoted_repeat1",
  [aux_sym_braced_body_repeat1] = "braced_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_LT_SLASH_GT] = anon_sym_LT_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attr_name] = sym_attr_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_token1] = aux_sym_quoted_token1,
  [aux_sym_quoted_token2] = aux_sym_quoted_token2,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_braced_body_token1] = aux_sym_braced_body_token1,
  [sym_text] = sym_text,
  [sym_source] = sym_source,
  [sym__node] = sym__node,
  [sym_jsx_element] = sym_jsx_element,
  [sym_jsx_self_closing] = sym_jsx_self_closing,
  [sym_jsx_fragment] = sym_jsx_fragment,
  [sym_jsx_open_tag] = sym_jsx_open_tag,
  [sym_jsx_close_tag] = sym_jsx_close_tag,
  [sym_attribute] = sym_attribute,
  [sym_attr_binding_quoted] = sym_attr_binding_quoted,
  [sym_attr_binding_braced] = sym_attr_binding_braced,
  [sym_attr_name_only] = sym_attr_name_only,
  [sym_quoted] = sym_quoted,
  [sym_braced_expression] = sym_braced_expression,
  [sym_braced_body] = sym_braced_body,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_jsx_self_closing_repeat1] = aux_sym_jsx_self_closing_repeat1,
  [aux_sym_quoted_repeat1] = aux_sym_quoted_repeat1,
  [aux_sym_braced_body_repeat1] = aux_sym_braced_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attr_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_braced_body_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_jsx_element] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_self_closing] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_binding_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_binding_braced] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_name_only] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jsx_self_closing_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 10,
  [38] = 8,
  [39] = 10,
  [40] = 8,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 24,
        '#', 11,
        '/', 4,
        '<', 13,
        '=', 22,
        '>', 19,
        '\\', 7,
        '{', 28,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(25);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 24,
        '#', 11,
        '/', 4,
        '<', 13,
        '=', 22,
        '>', 19,
        '\\', 7,
        '{', 28,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '{') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      if (lookahead == '>') ADVANCE(18);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_attr_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_quoted_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_quoted_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_quoted_token2);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_braced_body_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_braced_body_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attr_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_quoted_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(41),
    [sym__node] = STATE(6),
    [sym_jsx_element] = STATE(6),
    [sym_jsx_self_closing] = STATE(6),
    [sym_jsx_fragment] = STATE(6),
    [sym_jsx_open_tag] = STATE(3),
    [sym_braced_expression] = STATE(6),
    [aux_sym_source_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_GT] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(20), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_GT,
    ACTIONS(28), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_text,
    STATE(3), 1,
      sym_jsx_open_tag,
    ACTIONS(26), 2,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
    STATE(2), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [34] = 9,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(34), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LT_SLASH,
    ACTIONS(38), 1,
      sym_text,
    STATE(3), 1,
      sym_jsx_open_tag,
    STATE(11), 1,
      sym_jsx_close_tag,
    STATE(4), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [67] = 9,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      anon_sym_LT_SLASH,
    ACTIONS(40), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_text,
    STATE(3), 1,
      sym_jsx_open_tag,
    STATE(15), 1,
      sym_jsx_close_tag,
    STATE(2), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [100] = 8,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(48), 1,
      sym_text,
    STATE(3), 1,
      sym_jsx_open_tag,
    STATE(7), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [130] = 8,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_jsx_open_tag,
    STATE(2), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [160] = 8,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_GT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(52), 1,
      anon_sym_LT_SLASH_GT,
    STATE(3), 1,
      sym_jsx_open_tag,
    STATE(2), 6,
      sym__node,
      sym_jsx_element,
      sym_jsx_self_closing,
      sym_jsx_fragment,
      sym_braced_expression,
      aux_sym_source_repeat1,
  [190] = 2,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(56), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [203] = 2,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(60), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [216] = 2,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(64), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [229] = 2,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(68), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [242] = 2,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(72), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [255] = 5,
    ACTIONS(74), 1,
      anon_sym_SLASH_GT,
    ACTIONS(76), 1,
      anon_sym_GT,
    ACTIONS(78), 1,
      sym_attr_name,
    STATE(18), 2,
      sym_attribute,
      aux_sym_jsx_self_closing_repeat1,
    STATE(33), 3,
      sym_attr_binding_quoted,
      sym_attr_binding_braced,
      sym_attr_name_only,
  [274] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(82), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [287] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(86), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [300] = 2,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(90), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [313] = 5,
    ACTIONS(78), 1,
      sym_attr_name,
    ACTIONS(92), 1,
      anon_sym_SLASH_GT,
    ACTIONS(94), 1,
      anon_sym_GT,
    STATE(13), 2,
      sym_attribute,
      aux_sym_jsx_self_closing_repeat1,
    STATE(33), 3,
      sym_attr_binding_quoted,
      sym_attr_binding_braced,
      sym_attr_name_only,
  [332] = 4,
    ACTIONS(98), 1,
      sym_attr_name,
    ACTIONS(96), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
    STATE(18), 2,
      sym_attribute,
      aux_sym_jsx_self_closing_repeat1,
    STATE(33), 3,
      sym_attr_binding_quoted,
      sym_attr_binding_braced,
      sym_attr_name_only,
  [349] = 2,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(103), 6,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [362] = 5,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(109), 1,
      aux_sym_braced_body_token1,
    STATE(47), 1,
      sym_braced_body,
    STATE(26), 2,
      sym_braced_expression,
      aux_sym_braced_body_repeat1,
  [379] = 5,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      aux_sym_braced_body_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_braced_body,
    STATE(26), 2,
      sym_braced_expression,
      aux_sym_braced_body_repeat1,
  [396] = 2,
    ACTIONS(115), 1,
      sym_text,
    ACTIONS(113), 5,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [407] = 2,
    ACTIONS(119), 1,
      sym_text,
    ACTIONS(117), 5,
      sym_comment,
      anon_sym_LT,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [418] = 5,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      aux_sym_braced_body_token1,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_braced_body,
    STATE(26), 2,
      sym_braced_expression,
      aux_sym_braced_body_repeat1,
  [435] = 4,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 1,
      aux_sym_braced_body_token1,
    STATE(25), 2,
      sym_braced_expression,
      aux_sym_braced_body_repeat1,
  [449] = 4,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(133), 1,
      aux_sym_braced_body_token1,
    STATE(25), 2,
      sym_braced_expression,
      aux_sym_braced_body_repeat1,
  [463] = 2,
    ACTIONS(137), 1,
      anon_sym_EQ,
    ACTIONS(135), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [472] = 3,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(141), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [483] = 4,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_quoted,
    STATE(34), 1,
      sym_braced_expression,
  [496] = 3,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(149), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [507] = 3,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym_quoted_repeat1,
    ACTIONS(153), 2,
      aux_sym_quoted_token1,
      aux_sym_quoted_token2,
  [518] = 1,
    ACTIONS(156), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [524] = 1,
    ACTIONS(158), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [530] = 1,
    ACTIONS(160), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [536] = 1,
    ACTIONS(162), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [542] = 1,
    ACTIONS(164), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [548] = 2,
    ACTIONS(62), 1,
      aux_sym_braced_body_token1,
    ACTIONS(64), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [556] = 2,
    ACTIONS(54), 1,
      aux_sym_braced_body_token1,
    ACTIONS(56), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [564] = 1,
    ACTIONS(62), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [570] = 1,
    ACTIONS(54), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attr_name,
  [576] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [580] = 1,
    ACTIONS(168), 1,
      sym_identifier,
  [584] = 1,
    ACTIONS(170), 1,
      sym_identifier,
  [588] = 1,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
  [592] = 1,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
  [596] = 1,
    ACTIONS(176), 1,
      anon_sym_GT,
  [600] = 1,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 67,
  [SMALL_STATE(5)] = 100,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 190,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 229,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 255,
  [SMALL_STATE(14)] = 274,
  [SMALL_STATE(15)] = 287,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 313,
  [SMALL_STATE(18)] = 332,
  [SMALL_STATE(19)] = 349,
  [SMALL_STATE(20)] = 362,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 396,
  [SMALL_STATE(23)] = 407,
  [SMALL_STATE(24)] = 418,
  [SMALL_STATE(25)] = 435,
  [SMALL_STATE(26)] = 449,
  [SMALL_STATE(27)] = 463,
  [SMALL_STATE(28)] = 472,
  [SMALL_STATE(29)] = 483,
  [SMALL_STATE(30)] = 496,
  [SMALL_STATE(31)] = 507,
  [SMALL_STATE(32)] = 518,
  [SMALL_STATE(33)] = 524,
  [SMALL_STATE(34)] = 530,
  [SMALL_STATE(35)] = 536,
  [SMALL_STATE(36)] = 542,
  [SMALL_STATE(37)] = 548,
  [SMALL_STATE(38)] = 556,
  [SMALL_STATE(39)] = 564,
  [SMALL_STATE(40)] = 570,
  [SMALL_STATE(41)] = 576,
  [SMALL_STATE(42)] = 580,
  [SMALL_STATE(43)] = 584,
  [SMALL_STATE(44)] = 588,
  [SMALL_STATE(45)] = 592,
  [SMALL_STATE(46)] = 596,
  [SMALL_STATE(47)] = 600,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_expression, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_expression, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_self_closing, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_self_closing, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_expression, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_expression, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_fragment, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_fragment, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_self_closing, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_self_closing, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_fragment, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_fragment, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_self_closing_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_self_closing_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_close_tag, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_close_tag, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_open_tag, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_open_tag, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_open_tag, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_open_tag, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_body_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_braced_body_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_body_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_body, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_name_only, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_binding_quoted, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_binding_braced, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_crepusx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
