// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// Package crepuscularity — low-level ABI (generated). Link libcrepuscularity_abi.
package crepuscularity

/*
#cgo LDFLAGS: -lcrepuscularity_abi
#include "crepuscularity_abi.h"
*/
import "C"
