//! Moonshine JSX emitter, promoted from the CLI so external Rust projects can call it.
//!
//! HTML is the real production path (`build_site_wasm`). `--emit moonshine` writes
//! a real `@tschk/crepus-moonshine` app entry under `dist/`.

use crate::ir::{ViewIr, ViewNode, ViewStyle};

/// Emit a Moonshine app entry as real JSX, preserving the original class tokens
/// as `className` so UnoCSS/Tailwind styles the output.
///
/// Output is valid TSX: `App` + optional `mount` helper using `@tschk/moonshine/react`.
pub fn emit_moonshine_app(ir: &ViewIr) -> String {
    let children: String = ir
        .root
        .iter()
        .map(|n| emit_jsx_node(n, 3))
        .collect::<Vec<_>>()
        .join("\n");
    let mut body = format!(
        r#"// Generated by crepus web build --emit moonshine
import {{ createApp }} from "@tschk/moonshine/react";

export function App() {{
  return (
    <div data-crepus-root="true">
{children}
    </div>
  );
}}
"#
    );
    body.push_str(
        r##"
// Optional mount helper for Vite entry
export function mount(selector = "#app") {
  createApp({ root: App }).mount(selector);
}

export default App;
"##,
    );
    body
}

/// Emit the same JSX tree as [`emit_moonshine_app`] but as a named, importable
/// component instead of an app entry: no `createApp` import, no `mount` helper.
pub fn emit_moonshine_component(ir: &ViewIr, component_name: &str) -> String {
    let children: String = ir
        .root
        .iter()
        .map(|n| emit_jsx_node(n, 3))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// Generated by crepus web build --emit moonshine
export function {component_name}() {{
  return (
    <div data-crepus-root="true">
{children}
    </div>
  );
}}

export default {component_name};
"#
    )
}

/// JSON-escape a string for use inside a JSX expression container.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A string-valued JSX attribute, written the way a person writes it:
/// `name="value"`. The braced form is only used when the value cannot sit
/// inside a quoted literal, since `name={"value"}` is legal but not idiomatic.
fn attr(name: &str, value: &str) -> String {
    let needs_expr = value
        .chars()
        .any(|c| c == '"' || c == '\\' || (c as u32) < 0x20);
    if needs_expr {
        format!(" {name}={{{}}}", js_str(value))
    } else {
        format!(" {name}=\"{value}\"")
    }
}

/// A JSX text child, written literally rather than as `{"..."}`. Characters
/// JSX reads as markup or as an HTML entity force the braced form, because
/// literal text containing them would not round-trip.
fn jsx_text(content: &str) -> String {
    let needs_expr = content.is_empty()
        || content != content.trim()
        || content
            .chars()
            .any(|c| matches!(c, '{' | '}' | '<' | '>' | '&') || (c as u32) < 0x20);
    if needs_expr {
        format!("{{{}}}", js_str(content))
    } else {
        content.to_string()
    }
}

/// `className="..."` from the class tokens the parser preserved on the node.
fn class_attr(style: Option<&ViewStyle>) -> String {
    let classes = match style {
        Some(s) if !s.classes.is_empty() => s.classes.join(" "),
        _ => return String::new(),
    };
    attr("className", &classes)
}

fn opt_attr(name: &str, value: Option<&String>) -> String {
    match value {
        Some(v) => attr(name, v),
        None => String::new(),
    }
}

fn emit_children(children: &[ViewNode], indent: usize) -> String {
    children
        .iter()
        .map(|c| emit_jsx_node(c, indent))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Wrap `children` in `tag`, or self-close when there are none.
fn element(tag: &str, attrs: &str, children: &[ViewNode], indent: usize) -> String {
    let pad = "  ".repeat(indent);
    if children.is_empty() {
        return format!("{pad}<{tag}{attrs} />");
    }
    let inner = emit_children(children, indent + 1);
    format!("{pad}<{tag}{attrs}>\n{inner}\n{pad}</{tag}>")
}

fn emit_jsx_node(node: &ViewNode, indent: usize) -> String {
    let pad = "  ".repeat(indent);
    match node {
        ViewNode::Text { content, style, .. } => {
            format!(
                "{pad}<span{}>{}</span>",
                class_attr(style.as_ref()),
                jsx_text(content)
            )
        }
        ViewNode::Link {
            href,
            target,
            rel,
            style,
            children,
        } => {
            let attrs = format!(
                "{}{}{}",
                attr("href", href),
                opt_attr("target", target.as_ref()),
                opt_attr("rel", rel.as_ref()),
            );
            element("a", &format!("{attrs}{}", class_attr(style.as_ref())), children, indent)
        }
        ViewNode::Stack { style, children, .. } => {
            element("div", &class_attr(style.as_ref()), children, indent)
        }
        ViewNode::Scroll { style, children, .. } => {
            element("div", &class_attr(style.as_ref()), children, indent)
        }
        ViewNode::Dropzone { style, children, .. } => {
            element("div", &class_attr(style.as_ref()), children, indent)
        }
        ViewNode::List {
            ordered,
            style,
            children,
        } => element(
            if *ordered { "ol" } else { "ul" },
            &class_attr(style.as_ref()),
            children,
            indent,
        ),
        ViewNode::ListItem { style, children, .. } => {
            element("li", &class_attr(style.as_ref()), children, indent)
        }
        ViewNode::Button { label, style, .. } => format!(
            "{pad}<button type=\"button\"{}>{}</button>",
            class_attr(style.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Badge { label, tone, style, .. } => format!(
            "{pad}<span{}{}>{}</span>",
            class_attr(style.as_ref()),
            opt_attr("data-tone", tone.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Divider { style, .. } => {
            format!("{pad}<hr{} />", class_attr(style.as_ref()))
        }
        ViewNode::Spacer { style, .. } => {
            format!("{pad}<div aria-hidden=\"true\"{} />", class_attr(style.as_ref()))
        }
        ViewNode::Image {
            src, alt, style, ..
        } => format!(
            "{pad}<img{}{}{} />",
            attr("src", src),
            attr("alt", alt.as_deref().unwrap_or("")),
            class_attr(style.as_ref())
        ),
        ViewNode::WebView { src, style } => format!(
            "{pad}<iframe{}{} />",
            attr("src", src),
            class_attr(style.as_ref())
        ),
        ViewNode::Toggle {
            label,
            checked,
            style,
            ..
        } => format!(
            "{pad}<button type=\"button\" role=\"switch\" aria-checked={{{}}}{}>{}</button>",
            checked,
            class_attr(style.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Checkbox {
            label,
            checked,
            style,
            ..
        } => format!(
            "{pad}<label{}>\n{pad}  <input type=\"checkbox\" defaultChecked={{{}}} />\n{pad}  {}\n{pad}</label>",
            class_attr(style.as_ref()),
            checked,
            jsx_text(label)
        ),
        ViewNode::Slider {
            value,
            min,
            max,
            step,
            style,
            ..
        } => format!(
            "{pad}<input type=\"range\" defaultValue={{{value}}} min={{{min}}} max={{{max}}}{}{} />",
            step.map(|s| format!(" step={{{s}}}")).unwrap_or_default(),
            class_attr(style.as_ref())
        ),
        ViewNode::Progress {
            value, max, style, ..
        } => format!(
            "{pad}<progress value={{{value}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Meter {
            value,
            min,
            max,
            style,
            ..
        } => format!(
            "{pad}<meter value={{{value}}} min={{{min}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Input {
            placeholder,
            bind,
            secure,
            multiline,
            style,
            ..
        } => {
            let cls = class_attr(style.as_ref());
            let ph = attr("placeholder", placeholder);
            let name = attr("name", bind);
            if *multiline {
                format!("{pad}<textarea{ph}{name}{cls} />")
            } else {
                let ty = if *secure { "password" } else { "text" };
                format!("{pad}<input type=\"{ty}\"{ph}{name}{cls} />")
            }
        }
        ViewNode::Picker {
            options,
            bind,
            style,
            ..
        } => {
            let opts: String = options
                .iter()
                .map(|o| {
                    format!(
                        "{pad}  <option{}>{}</option>",
                        attr("value", &o.value),
                        jsx_text(&o.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<select{}{}>\n{opts}\n{pad}</select>",
                attr("name", bind),
                class_attr(style.as_ref())
            )
        }
        ViewNode::FilePicker { label, style, .. } => format!(
            "{pad}<label{}>\n{pad}  <input type=\"file\" />\n{pad}  {}\n{pad}</label>",
            class_attr(style.as_ref()),
            jsx_text(label)
        ),
        ViewNode::SlotRotate {
            phrases,
            interval_ms,
            style,
        } => format!(
            "{pad}<span{} data-interval-ms={{{interval_ms}}}{}>{}</span>",
            attr("data-crepus-slot-rotate", &phrases.join("|")),
            class_attr(style.as_ref()),
            jsx_text(phrases.first().map(String::as_str).unwrap_or(""))
        ),
        ViewNode::Tabs { tabs, style, .. } => {
            let cls = class_attr(style.as_ref());
            let buttons: String = tabs
                .iter()
                .map(|t| {
                    format!(
                        "{pad}    <button type=\"button\" role=\"tab\">{}</button>",
                        jsx_text(&t.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            let panels: String = tabs
                .iter()
                .map(|t| {
                    format!(
                        "{pad}  <div role=\"tabpanel\">\n{}\n{pad}  </div>",
                        emit_children(&t.children, indent + 2)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<div{cls}>\n{pad}  <div role=\"tablist\">\n{buttons}\n{pad}  </div>\n{panels}\n{pad}</div>"
            )
        }
        // Control flow was not resolvable at build time; emit the static branch and
        // record the original expression so the source intent survives in the DOM.
        ViewNode::If {
            condition,
            then_children,
            style,
            ..
        } => {
            let attrs = format!(
                "{}{}",
                attr("data-crepus-if", condition),
                class_attr(style.as_ref())
            );
            element("div", &attrs, then_children, indent)
        }
        ViewNode::ForEach {
            bind,
            item_name,
            item_body,
            style,
        } => {
            let attrs = format!(
                "{}{}{}",
                attr("data-crepus-for-each", bind),
                attr("data-crepus-item", item_name),
                class_attr(style.as_ref())
            );
            element("div", &attrs, item_body, indent)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::render_template_to_ir;
    use crepuscularity_core::context::TemplateContext;

    fn sample_ir() -> ViewIr {
        let source = r#"stack col gap-2
 text "hi"
 button "Go"
"#;
        render_template_to_ir(source, &TemplateContext::new()).expect("ir")
    }

    #[test]
    fn moonshine_emit_writes_real_jsx_with_classnames() {
        let body = emit_moonshine_app(&sample_ir());
        assert!(body.contains("@tschk/moonshine/react"));
        assert!(body.contains("createApp"));
        assert!(body.contains("export function App"));
        assert!(body.contains("export function mount"));
        assert!(body.contains("data-crepus-root=\"true\""));
        // Real elements, not an IR blob handed to a runtime renderer.
        assert!(body.contains("<div className=\"col gap-2\">"));
        assert!(body.contains("<span>hi</span>"));
        assert!(body.contains("<button type=\"button\">Go</button>"));
        assert!(!body.contains("renderCrepusIr"));
        assert!(!body.contains("satisfies ViewIr"));
        assert!(!body.contains("TODO"));
    }

    #[test]
    fn moonshine_emit_preserves_anchor_href_and_classes() {
        let source =
            "a href=\"https://example.com\" no-underline text-zinc-100\n span \"crepuscularity\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(body.contains("<a href=\"https://example.com\""));
        assert!(body.contains("className=\"no-underline text-zinc-100\""));
        assert!(body.contains(">crepuscularity</span>"));
    }

    #[test]
    fn text_containing_jsx_metacharacters_stays_in_an_expression() {
        // `{`, `}`, `<`, `>` and `&` are markup or entity syntax in a JSX text
        // child, so this content cannot be written literally.
        let source = "text \"a < b && c > d\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(body.contains(r#"{"a < b && c > d"}"#), "{body}");
    }

    #[test]
    fn attribute_containing_a_quote_stays_in_an_expression() {
        let source = "a href=\"/a\\\"b\"\n span \"x\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(!body.contains(r#"href="/a"b""#), "{body}");
    }

    #[test]
    fn component_emitter_uses_named_component() {
        let body = emit_moonshine_component(&sample_ir(), "Card");
        assert!(body.contains("export function Card"));
        assert!(body.contains("export default Card;"));
    }

    #[test]
    fn component_emitter_omits_create_app_and_mount() {
        let body = emit_moonshine_component(&sample_ir(), "Card");
        assert!(!body.contains("createApp"));
        assert!(!body.contains("export function mount"));
        assert!(!body.contains("@tschk/moonshine/react"));
    }

    #[test]
    fn component_emitter_renders_same_markup_as_app_emitter() {
        let ir = sample_ir();
        let app_body = emit_moonshine_app(&ir);
        let component_body = emit_moonshine_component(&ir, "Card");
        assert!(app_body.contains("<div className=\"col gap-2\">"));
        assert!(component_body.contains("<div className=\"col gap-2\">"));
        assert!(app_body.contains("<span>hi</span>"));
        assert!(component_body.contains("<span>hi</span>"));
        assert!(app_body.contains("<button type=\"button\">Go</button>"));
        assert!(component_body.contains("<button type=\"button\">Go</button>"));
    }
}
