[[targets]]
type = "native"
id = "mobile-app"

[targets.ios]
bundle_id = "dev.crepuscularity.mobile-app"
scheme = "MobileApp"
xcodegen_spec = "project.yml"
destination = "platform=iOS Simulator,name=iPhone 16,OS=latest"

[targets.android]
application_id = "dev.crepuscularity.mobileapp"
namespace = "dev.crepuscularity.mobileapp"
