// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// Kotlin/JVM — same JNI surface as AbiGenerated.java
object AbiGenerated {
    init {
        System.loadLibrary("crepuscularity_abi")
    }
    external fun crepus_session_new(): Long
    external fun crepus_session_free(session: Long)
    external fun crepus_session_set_template_string(session: Long, templateUtf8: String, baseDirUtf8: String?): Int
    external fun crepus_session_set_context_json(session: Long, contextJsonUtf8: String): Int
    external fun crepus_session_render_ir_json(session: Long): String
    external fun crepus_session_dispatch_event_json(session: Long, eventJsonUtf8: String): String
}
