[package]
name = "crepuscularity-lvgl"
version = "0.1.10"
edition = "2021"
license = "ISC"
description = "LVGL Pro XML generator for the Crepuscularity .crepus DSL."
repository = "https://github.com/tschk/crepuscularity"
readme = "../../README.md"

[dependencies]
crepuscularity-core = { path = "../crepuscularity-core", version = "0.5.0" }

[dev-dependencies]
tempfile = { workspace = true }
