[package]
name = "local-scrobbler"
version = "0.1.0"
edition = "2021"
publish = false
license = "ISC"

[workspace]

[lib]
name = "local_scrobbler"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
crepuscularity-gpui = { path = "../../../crates/crepuscularity-gpui" }
gpui = { workspace = true }
gpui_platform = { workspace = true }
