// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

<?php
// FFI — PHP 7.4+; set CREPUS_ABI_LIB to libcrepuscularity_abi path
final class AbiGenerated {
    private static ?\FFI $ffi = null;

    public static function ffi(): \FFI {
        if (self::$ffi === null) {
            $lib = getenv('CREPUS_ABI_LIB') ?: 'libcrepuscularity_abi.dylib';
            self::$ffi = \FFI::cdef(
                'typedef struct CrepusSession CrepusSession;
                 CrepusSession *crepus_session_new(void);
                 void crepus_session_free(CrepusSession *session);
                 char *crepus_session_render_ir_json(CrepusSession *session);
                 void crepus_string_free(char *ptr);',
                $lib
            );
        }
        return self::$ffi;
    }
}
