// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// JNI stubs — load libcrepuscularity_abi and declare native methods (fill via javac -h).
// Include path: copy or symlink crepuscularity_abi.h into jni include dir.

public final class AbiGenerated {
    static {
        System.loadLibrary("crepuscularity_abi");
    }

    public static native long crepus_session_new();
    public static native void crepus_session_free(long session);
    public static native int crepus_session_set_template_string(long session, String templateUtf8, String baseDirUtf8);
    public static native int crepus_session_set_context_json(long session, String contextJsonUtf8);
    public static native String crepus_session_render_ir_json(long session);
    public static native String crepus_session_dispatch_event_json(long session, String eventJsonUtf8);
}
