// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// Bun/Node: use koffi or bun:ffi against libcrepuscularity_abi
// import koffi from "koffi";
// const lib = koffi.load(process.env.CREPUS_ABI_LIB ?? "libcrepuscularity_abi.dylib");
// export const crepus_session_new = lib.func("void* crepus_session_new()");
export {};
