[package]
name = "embedded-dashboard"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[dependencies]
crepuscularity-embedded = { path = "../../crates/crepuscularity-embedded", version = "0.1.15", features = ["std"] }

[build-dependencies]
crepuscularity-core = { path = "../../crates/crepuscularity-core", version = "0.4.16" }

[[test]]
name = "smoke"
path = "tests/smoke.rs"
