[package]
name = "local-scrobbler"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
name = "local_scrobbler"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
crepuscularity-gpui = { path = "../../crates/crepuscularity-gpui" }
gpui = { version = "=0.2.2", default-features = false, features = ["font-kit"] }
